//! Conditions (intervening-"if", CR 603.4; resolution checks) and durations (how long a
//! continuous effect lasts, CR 611).

use super::target::CardFilter;
use super::value::{PlayerRef, ValueExpr};
use crate::basics::Zone;
use serde::{Deserialize, Serialize};

/// A boolean condition evaluated against game state — used for intervening-"if" triggers
/// (CR 603.4, checked at trigger time AND on resolution) and conditional effects.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum Condition {
    /// Always true (the default for triggers with no "if").
    Always,
    Not(Box<Condition>),
    All(Vec<Condition>),
    AnyOf(Vec<Condition>),
    /// `count(matching objects in zone) >= n`.
    CountAtLeast {
        zone: Zone,
        filter: CardFilter,
        controller: Option<PlayerRef>,
        n: ValueExpr,
    },
    /// A player's life total is at least / at most a value.
    LifeAtLeast { who: PlayerRef, n: ValueExpr },
    LifeAtMost { who: PlayerRef, n: ValueExpr },
    /// It is the controller's turn.
    YourTurn,
    /// The named player has gained one or more life this turn (CR 118.9) — the SoS "Infusion" gate.
    GainedLifeThisTurn { who: PlayerRef },
    /// Compare two values.
    ValueAtLeast(ValueExpr, ValueExpr),
}

/// How long a continuous effect generated by resolution lasts (CR 611.2).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Duration {
    /// One-shot: applies and is done (no lingering continuous effect).
    OneShot,
    /// "until end of turn" (CR 514.2 cleanup ends it).
    UntilEndOfTurn,
    /// "until your next turn".
    UntilYourNextTurn,
    /// "this turn".
    ThisTurn,
    /// As long as the source remains (static ability of a permanent).
    WhileSourcePresent,
    /// Permanent / for the rest of the game.
    Permanent,
}
