//! SOS (Edge of … "sos") — first-printing-set folder.

use crate::cards::CardDb;

pub mod additive_evolution;
pub mod banishing_betrayal;
pub mod blech_loafing_pest;
pub mod bogwater_lumaret;
pub mod burrog_banemaker;
pub mod chase_inspiration;
pub mod chelonian_tackle;
pub mod cost_of_brilliance;
pub mod cuboid_colony;
pub mod dinas_guidance;
pub mod dissection_practice;
pub mod eager_glyphmage;
pub mod efflorescence;
pub mod environmental_scientist;
pub mod erode;
pub mod exhibition_tidecaller;
pub mod expressive_firedancer;
pub mod flow_state;
pub mod fields_of_strife;
pub mod foolish_fate;
pub mod forum_of_amity;
pub mod graduation_day;
pub mod grapple_with_death;
pub mod harsh_annotation;
pub mod hungry_graffalon;
pub mod imperious_inkmage;
pub mod informed_inkwright;
pub mod inkling_mascot;
pub mod interjection;
pub mod lecturing_scornmage;
pub mod masterful_flourish;
pub mod melancholic_poet;
pub mod mindful_biomancer;
pub mod molten_core_maestro;
pub mod muse_seeker;
pub mod muses_encouragement;
pub mod noxious_newt;
pub mod old_growth_educator;
pub mod oracles_restoration;
pub mod paradox_gardens;
pub mod pest_mascot;
pub mod planar_engineering;
pub mod poisoners_apprentice;
pub mod primary_research;
pub mod proctors_gaze;
pub mod rapturous_moment;
pub mod rearing_embermare;
pub mod rehearsed_debater;
pub mod shattered_acolyte;
pub mod shopkeepers_bane;
pub mod silverquill_charm;
pub mod sneering_shadewriter;
pub mod spectacular_skywhale;
pub mod spectacle_summit;
pub mod stadium_tidalmage;
pub mod startled_relic_sloth;
pub mod stress_dream;
pub mod strixhaven_skycoach;
pub mod stirring_hopesinger;
pub mod tackle_artist;
pub mod thunderdrum_soloist;
pub mod titans_grave;
pub mod tenured_concocter;
pub mod textbook_tabulator;
pub mod traumatic_critique;
pub mod ulna_alley_shopkeep;
pub mod unsubtle_mockery;
pub mod vibrant_outburst;
pub mod wander_off;
pub mod witherbloom_charm;
pub mod zealous_lorecaster;

pub fn register(db: &mut CardDb) {
    additive_evolution::register(db);
    banishing_betrayal::register(db);
    blech_loafing_pest::register(db);
    bogwater_lumaret::register(db);
    burrog_banemaker::register(db);
    chase_inspiration::register(db);
    chelonian_tackle::register(db);
    cost_of_brilliance::register(db);
    cuboid_colony::register(db);
    dinas_guidance::register(db);
    dissection_practice::register(db);
    eager_glyphmage::register(db);
    efflorescence::register(db);
    environmental_scientist::register(db);
    erode::register(db);
    exhibition_tidecaller::register(db);
    expressive_firedancer::register(db);
    flow_state::register(db);
    fields_of_strife::register(db);
    foolish_fate::register(db);
    forum_of_amity::register(db);
    graduation_day::register(db);
    grapple_with_death::register(db);
    harsh_annotation::register(db);
    hungry_graffalon::register(db);
    imperious_inkmage::register(db);
    informed_inkwright::register(db);
    inkling_mascot::register(db);
    interjection::register(db);
    lecturing_scornmage::register(db);
    masterful_flourish::register(db);
    melancholic_poet::register(db);
    mindful_biomancer::register(db);
    molten_core_maestro::register(db);
    muse_seeker::register(db);
    muses_encouragement::register(db);
    noxious_newt::register(db);
    old_growth_educator::register(db);
    oracles_restoration::register(db);
    paradox_gardens::register(db);
    pest_mascot::register(db);
    planar_engineering::register(db);
    poisoners_apprentice::register(db);
    primary_research::register(db);
    proctors_gaze::register(db);
    rapturous_moment::register(db);
    rearing_embermare::register(db);
    rehearsed_debater::register(db);
    shattered_acolyte::register(db);
    shopkeepers_bane::register(db);
    silverquill_charm::register(db);
    sneering_shadewriter::register(db);
    spectacular_skywhale::register(db);
    spectacle_summit::register(db);
    stadium_tidalmage::register(db);
    startled_relic_sloth::register(db);
    stress_dream::register(db);
    strixhaven_skycoach::register(db);
    stirring_hopesinger::register(db);
    tackle_artist::register(db);
    thunderdrum_soloist::register(db);
    titans_grave::register(db);
    tenured_concocter::register(db);
    textbook_tabulator::register(db);
    traumatic_critique::register(db);
    ulna_alley_shopkeep::register(db);
    unsubtle_mockery::register(db);
    vibrant_outburst::register(db);
    wander_off::register(db);
    witherbloom_charm::register(db);
    zealous_lorecaster::register(db);
}
