//! SOS (Edge of … "sos") — first-printing-set folder.

use crate::cards::CardDb;

pub mod aberrant_manawurm;
pub mod emeritus_of_conflict;
pub mod joined_researchers;
pub mod jadzi_steward_of_fate;
pub mod harmonized_trio;
pub mod grave_researcher;
pub mod leech_collector;
pub mod goblin_glasswright;
pub mod group_project;
pub mod elite_interceptor;
pub mod end_of_the_hunt;
pub mod improvisation_capstone;
pub mod infirmary_healer;
pub mod emeritus_of_abundance;
pub mod emeritus_of_ideation;
pub mod emeritus_of_truce;
pub mod emeritus_of_woe;
pub mod scheming_silvertongue;
pub mod seize_the_spoils;
pub mod soaring_stoneglider;
pub mod skycoach_conductor;
pub mod abigale_poet_laureate;
pub mod kirol_history_buff;
pub mod sanar_unfinished_genius;
pub mod spiritcall_enthusiast;
pub mod tam_observant_sequencer;
pub mod blazing_firesinger;
pub mod campus_composer;
pub mod cheerful_osteomancer;
pub mod honorbound_page;
pub mod landscape_painter;
pub mod maelstrom_artisan;
pub mod quandrix_charm;
pub mod quill_blade_laureate;
pub mod spellbook_seeker;
pub mod strife_scholar;
pub mod studious_first_year;
pub mod abstract_paintmage;
pub mod additive_evolution;
pub mod adventurous_eater;
pub mod ajanis_response;
pub mod antiquities_on_the_loose;
pub mod applied_geometry;
pub mod arcane_omens;
pub mod arnyn_deathbloom_botanist;
pub mod artistic_process;
pub mod ascendant_dustspeaker;
pub mod banishing_betrayal;
pub mod brush_off;
pub mod berta_wise_extrapolator;
pub mod blech_loafing_pest;
pub mod bogwater_lumaret;
pub mod burrog_banemaker;
pub mod cauldron_of_essence;
pub mod charging_strifeknight;
pub mod chase_inspiration;
pub mod chelonian_tackle;
pub mod colorstorm_stallion;
pub mod colossus_of_the_blood_age;
pub mod comforting_counsel;
pub mod cost_of_brilliance;
pub mod cuboid_colony;
pub mod decorum_dissertation;
pub mod deluge_virtuoso;
pub mod diary_of_dreams;
pub mod dig_site_inventory;
pub mod dinas_guidance;
pub mod daydream;
pub mod dissection_practice;
pub mod duel_tactics;
pub mod eager_glyphmage;
pub mod echocasting_symposium;
pub mod efflorescence;
pub mod elemental_mascot;
pub mod embrace_the_paradox;
pub mod emil_vastlands_roamer;
pub mod encouraging_aviator;
pub mod environmental_scientist;
pub mod erode;
pub mod essenceknit_scholar;
pub mod eternal_student;
pub mod exhibition_tidecaller;
pub mod expressive_firedancer;
pub mod fractal_anomaly;
pub mod fractal_mascot;
pub mod fractal_tender;
pub mod flow_state;
pub mod fields_of_strife;
pub mod follow_the_lumarets;
pub mod fix_whats_broken;
pub mod foolish_fate;
pub mod forum_necroscribe;
pub mod forum_of_amity;
pub mod garrison_excavator;
pub mod geometers_arthropod;
pub mod germination_practicum;
pub mod glorious_decay;
pub mod graduation_day;
pub mod grapple_with_death;
pub mod growth_curve;
pub mod hardened_academic;
pub mod harsh_annotation;
pub mod heated_argument;
pub mod homesickness;
pub mod hungry_graffalon;
pub mod hydro_channeler;
pub mod imperious_inkmage;
pub mod impractical_joke;
pub mod informed_inkwright;
pub mod inkling_mascot;
pub mod inkshape_demonstrator;
pub mod interjection;
pub mod killians_confidence;
pub mod lecturing_scornmage;
pub mod living_history;
pub mod lluwen_exchange_student;
pub mod lorehold_charm;
pub mod mage_tower_referee;
pub mod magmablood_archaic;
pub mod masterful_flourish;
pub mod matterbending_mage;
pub mod melancholic_poet;
pub mod mindful_biomancer;
pub mod molten_core_maestro;
pub mod molten_note;
pub mod moment_of_reckoning;
pub mod muse_seeker;
pub mod muses_encouragement;
pub mod noxious_newt;
pub mod old_growth_educator;
pub mod oracles_restoration;
pub mod orysa_tide_choreographer;
pub mod paradox_gardens;
pub mod pest_mascot;
pub mod pigment_wrangler;
pub mod planar_engineering;
pub mod owlin_historian;
pub mod paradox_surveyor;
pub mod pestbrood_sloth;
pub mod poisoners_apprentice;
pub mod pensive_professor;
pub mod postmortem_professor;
pub mod potioners_trove;
pub mod professor_dellian_fel;
pub mod practiced_scrollsmith;
pub mod primary_research;
pub mod prismari_charm;
pub mod procrastinate;
pub mod proctors_gaze;
pub mod pterafractyl;
pub mod pull_from_the_grave;
pub mod pursue_the_past;
pub mod rapturous_moment;
pub mod rancorous_archaic;
pub mod ral_zarek_guest_lecturer;
pub mod restoration_seminar;
pub mod run_behind;
pub mod rearing_embermare;
pub mod rapier_wit;
pub mod rehearsed_debater;
pub mod render_speechless;
pub mod scathing_shadelock;
pub mod shattered_acolyte;
pub mod shopkeepers_bane;
pub mod send_in_the_pest;
pub mod silverquill_charm;
pub mod snarl_song;
pub mod sneering_shadewriter;
pub mod spectacular_skywhale;
pub mod spectacle_summit;
pub mod stadium_tidalmage;
pub mod stand_up_for_yourself;
pub mod spirit_mascot;
pub mod splatter_technique;
pub mod startled_relic_sloth;
pub mod stone_docent;
pub mod stress_dream;
pub mod strixhaven_skycoach;
pub mod stirring_honormancer;
pub mod stirring_hopesinger;
pub mod suspend_aggression;
pub mod summoned_dromedary;
pub mod tackle_artist;
pub mod teachers_pest;
pub mod the_dawning_archaic;
pub mod thunderdrum_soloist;
pub mod transcendent_archaic;
pub mod together_as_one;
pub mod tome_blast;
pub mod thornfist_striker;
pub mod titans_grave;
pub mod tenured_concocter;
pub mod textbook_tabulator;
pub mod topiary_lecturer;
pub mod tragedy_feaster;
pub mod traumatic_critique;
pub mod ulna_alley_shopkeep;
pub mod unsubtle_mockery;
pub mod vastlands_scavenger;
pub mod vibrant_outburst;
pub mod vicious_rivalry;
pub mod visionarys_dance;
pub mod wildgrowth_archaic;
pub mod wander_off;
pub mod wild_hypothesis;
pub mod wilt_in_the_heat;
pub mod witherbloom_charm;
pub mod withering_curse;
pub mod zealous_lorecaster;

pub fn register(db: &mut CardDb) {
    aberrant_manawurm::register(db);
    emeritus_of_conflict::register(db);
    joined_researchers::register(db);
    jadzi_steward_of_fate::register(db);
    harmonized_trio::register(db);
    grave_researcher::register(db);
    leech_collector::register(db);
    goblin_glasswright::register(db);
    group_project::register(db);
    elite_interceptor::register(db);
    end_of_the_hunt::register(db);
    improvisation_capstone::register(db);
    infirmary_healer::register(db);
    emeritus_of_abundance::register(db);
    emeritus_of_ideation::register(db);
    emeritus_of_truce::register(db);
    emeritus_of_woe::register(db);
    scheming_silvertongue::register(db);
    seize_the_spoils::register(db);
    soaring_stoneglider::register(db);
    skycoach_conductor::register(db);
    abigale_poet_laureate::register(db);
    kirol_history_buff::register(db);
    sanar_unfinished_genius::register(db);
    spiritcall_enthusiast::register(db);
    tam_observant_sequencer::register(db);
    blazing_firesinger::register(db);
    campus_composer::register(db);
    cheerful_osteomancer::register(db);
    honorbound_page::register(db);
    landscape_painter::register(db);
    maelstrom_artisan::register(db);
    quill_blade_laureate::register(db);
    spellbook_seeker::register(db);
    strife_scholar::register(db);
    studious_first_year::register(db);
    abstract_paintmage::register(db);
    additive_evolution::register(db);
    adventurous_eater::register(db);
    ajanis_response::register(db);
    antiquities_on_the_loose::register(db);
    applied_geometry::register(db);
    arcane_omens::register(db);
    arnyn_deathbloom_botanist::register(db);
    artistic_process::register(db);
    ascendant_dustspeaker::register(db);
    banishing_betrayal::register(db);
    brush_off::register(db);
    berta_wise_extrapolator::register(db);
    blech_loafing_pest::register(db);
    bogwater_lumaret::register(db);
    burrog_banemaker::register(db);
    cauldron_of_essence::register(db);
    charging_strifeknight::register(db);
    chase_inspiration::register(db);
    chelonian_tackle::register(db);
    colorstorm_stallion::register(db);
    colossus_of_the_blood_age::register(db);
    comforting_counsel::register(db);
    cost_of_brilliance::register(db);
    cuboid_colony::register(db);
    decorum_dissertation::register(db);
    deluge_virtuoso::register(db);
    diary_of_dreams::register(db);
    dig_site_inventory::register(db);
    daydream::register(db);
    dinas_guidance::register(db);
    dissection_practice::register(db);
    duel_tactics::register(db);
    eager_glyphmage::register(db);
    echocasting_symposium::register(db);
    efflorescence::register(db);
    elemental_mascot::register(db);
    embrace_the_paradox::register(db);
    emil_vastlands_roamer::register(db);
    encouraging_aviator::register(db);
    environmental_scientist::register(db);
    erode::register(db);
    essenceknit_scholar::register(db);
    eternal_student::register(db);
    exhibition_tidecaller::register(db);
    expressive_firedancer::register(db);
    fractal_anomaly::register(db);
    fractal_mascot::register(db);
    fractal_tender::register(db);
    flow_state::register(db);
    fields_of_strife::register(db);
    follow_the_lumarets::register(db);
    fix_whats_broken::register(db);
    foolish_fate::register(db);
    forum_necroscribe::register(db);
    forum_of_amity::register(db);
    garrison_excavator::register(db);
    geometers_arthropod::register(db);
    germination_practicum::register(db);
    glorious_decay::register(db);
    graduation_day::register(db);
    grapple_with_death::register(db);
    growth_curve::register(db);
    hardened_academic::register(db);
    harsh_annotation::register(db);
    heated_argument::register(db);
    homesickness::register(db);
    hungry_graffalon::register(db);
    hydro_channeler::register(db);
    imperious_inkmage::register(db);
    impractical_joke::register(db);
    informed_inkwright::register(db);
    inkling_mascot::register(db);
    inkshape_demonstrator::register(db);
    interjection::register(db);
    killians_confidence::register(db);
    lecturing_scornmage::register(db);
    living_history::register(db);
    lluwen_exchange_student::register(db);
    lorehold_charm::register(db);
    mage_tower_referee::register(db);
    magmablood_archaic::register(db);
    masterful_flourish::register(db);
    matterbending_mage::register(db);
    melancholic_poet::register(db);
    mindful_biomancer::register(db);
    molten_core_maestro::register(db);
    molten_note::register(db);
    moment_of_reckoning::register(db);
    muse_seeker::register(db);
    muses_encouragement::register(db);
    noxious_newt::register(db);
    old_growth_educator::register(db);
    oracles_restoration::register(db);
    orysa_tide_choreographer::register(db);
    paradox_gardens::register(db);
    pest_mascot::register(db);
    pigment_wrangler::register(db);
    planar_engineering::register(db);
    owlin_historian::register(db);
    paradox_surveyor::register(db);
    pestbrood_sloth::register(db);
    poisoners_apprentice::register(db);
    pensive_professor::register(db);
    postmortem_professor::register(db);
    potioners_trove::register(db);
    professor_dellian_fel::register(db);
    practiced_scrollsmith::register(db);
    primary_research::register(db);
    prismari_charm::register(db);
    quandrix_charm::register(db);
    procrastinate::register(db);
    proctors_gaze::register(db);
    pterafractyl::register(db);
    pull_from_the_grave::register(db);
    pursue_the_past::register(db);
    rapturous_moment::register(db);
    rancorous_archaic::register(db);
    ral_zarek_guest_lecturer::register(db);
    restoration_seminar::register(db);
    run_behind::register(db);
    rearing_embermare::register(db);
    rapier_wit::register(db);
    rehearsed_debater::register(db);
    render_speechless::register(db);
    scathing_shadelock::register(db);
    shattered_acolyte::register(db);
    shopkeepers_bane::register(db);
    send_in_the_pest::register(db);
    silverquill_charm::register(db);
    snarl_song::register(db);
    sneering_shadewriter::register(db);
    spectacular_skywhale::register(db);
    spectacle_summit::register(db);
    stadium_tidalmage::register(db);
    stand_up_for_yourself::register(db);
    spirit_mascot::register(db);
    splatter_technique::register(db);
    startled_relic_sloth::register(db);
    stone_docent::register(db);
    stress_dream::register(db);
    strixhaven_skycoach::register(db);
    stirring_honormancer::register(db);
    stirring_hopesinger::register(db);
    suspend_aggression::register(db);
    summoned_dromedary::register(db);
    tackle_artist::register(db);
    teachers_pest::register(db);
    the_dawning_archaic::register(db);
    thunderdrum_soloist::register(db);
    transcendent_archaic::register(db);
    together_as_one::register(db);
    tome_blast::register(db);
    thornfist_striker::register(db);
    titans_grave::register(db);
    tenured_concocter::register(db);
    textbook_tabulator::register(db);
    topiary_lecturer::register(db);
    tragedy_feaster::register(db);
    traumatic_critique::register(db);
    ulna_alley_shopkeep::register(db);
    unsubtle_mockery::register(db);
    vastlands_scavenger::register(db);
    vibrant_outburst::register(db);
    vicious_rivalry::register(db);
    visionarys_dance::register(db);
    wander_off::register(db);
    wild_hypothesis::register(db);
    wildgrowth_archaic::register(db);
    wilt_in_the_heat::register(db);
    witherbloom_charm::register(db);
    withering_curse::register(db);
    zealous_lorecaster::register(db);
}
