#!/usr/bin/env python3
"""Generate Rust enums for MTG sub/supertypes from Scryfall's type catalogs.

Magic's subtypes and supertypes are a closed, CR-enumerated set (CR 205.3/205.4). Modeling
them as `Vec<String>` is typo-prone (the CR-305.6 mana code matched the literal "Forest"); this
emits type-safe enums instead. Run:

    python3 scripts/gen_subtypes.py > crates/mtg-core/src/basics/subtypes.rs

Sources the authoritative lists from https://api.scryfall.com/catalog/{...}-types so the 334
creature types etc. aren't hand-maintained; re-run when a new set adds a type. The generated
file defines one enum per category + a tagged `Subtype`, each with Display + FromStr + serde
**as the canonical string** (so the JSON the web client sees stays a plain type-line string,
no protocol change) + `From<Inner> for Subtype`.
"""
import json
import sys
import urllib.request

UA = "mtgenv/0.1 (https://github.com/misprit7/mtgenv; local dev)"
# (catalog endpoint, Rust enum name)
CATS = [
    ("supertypes", "Supertype"),
    ("land-types", "LandType"),
    ("creature-types", "CreatureType"),
    ("artifact-types", "ArtifactType"),
    ("enchantment-types", "EnchantmentType"),
    ("planeswalker-types", "PlaneswalkerType"),
    ("spell-types", "SpellType"),
]
# Which enums are subtypes (Supertype is separate, not part of `Subtype`).
SUBTYPE_ENUMS = ["LandType", "CreatureType", "ArtifactType", "EnchantmentType",
                 "PlaneswalkerType", "SpellType"]


def fetch(cat):
    req = urllib.request.Request(f"https://api.scryfall.com/catalog/{cat}",
                                 headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req) as r:
        return json.load(r)["data"]


def ident(s):
    """Canonical string -> a valid PascalCase Rust identifier."""
    out, cap = [], True
    for ch in s:
        if ch.isalnum():
            out.append(ch.upper() if cap else ch)
            cap = False
        elif ch == "'":  # apostrophe: drop without a word break ("Urza's" -> "Urzas")
            continue
        else:  # space, hyphen, etc. -> word break (dropped)
            cap = True
    name = "".join(out)
    if name and name[0].isdigit():
        name = "T" + name
    return name


def emit_enum(name, values):
    # (identifier, canonical) pairs, deduped on identifier.
    seen, pairs = set(), []
    for v in values:
        i = ident(v)
        if i in seen:
            sys.stderr.write(f"warn: identifier collision {i} ({v}) — skipped\n")
            continue
        seen.add(i)
        pairs.append((i, v))
    print(f"subtype_enum! {{ {name},")
    for i, v in pairs:
        print(f"    {i} => {json.dumps(v)},")
    print("}\n")


def main():
    cats = {name: fetch(cat) for cat, name in CATS}
    print("// @generated by scripts/gen_subtypes.py from Scryfall type catalogs — do not edit by hand.")
    print("// Regenerate when a set introduces a new subtype. CR 205.3 (subtypes) / 205.4 (supertypes).")
    print("#![cfg_attr(rustfmt, rustfmt::skip)]")
    print("use serde::{Deserialize, Serialize};\n")
    # A macro that gives each enum Display + FromStr + serde-as-canonical-string.
    print("""/// Defines a closed type enum with Display/FromStr/serde all keyed to the canonical
/// MTG string (so the wire format stays a plain type-line token).
macro_rules! subtype_enum {
    ($name:ident, $($variant:ident => $disp:literal,)*) => {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
        pub enum $name { $($variant,)* }
        impl $name {
            pub fn as_str(&self) -> &'static str { match self { $(Self::$variant => $disp,)* } }
        }
        impl core::fmt::Display for $name {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result { f.write_str(self.as_str()) }
        }
        impl core::str::FromStr for $name {
            type Err = ();
            fn from_str(s: &str) -> Result<Self, ()> { Ok(match s { $($disp => Self::$variant,)* _ => return Err(()) }) }
        }
        impl Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> { s.serialize_str(self.as_str()) }
        }
        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let s = String::deserialize(d)?;
                s.parse().map_err(|_| serde::de::Error::custom(format!("unknown {}: {s}", stringify!($name))))
            }
        }
    };
}
""")
    for _, name in CATS:
        emit_enum(name, cats[name])

    # The tagged Subtype: one of the subtype categories (Supertype is separate).
    print("/// Any printable subtype (CR 205.3), tagged by the category it belongs to.")
    print("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]")
    print("pub enum Subtype {")
    for name in SUBTYPE_ENUMS:
        print(f"    {name.replace('Type','')}({name}),")
    print("}\n")
    # From<Inner> for Subtype + Display + FromStr (try each category) + serde-as-string.
    for name in SUBTYPE_ENUMS:
        var = name.replace("Type", "")
        print(f"impl From<{name}> for Subtype {{ fn from(v: {name}) -> Self {{ Subtype::{var}(v) }} }}")
    print("""impl Subtype {
    pub fn as_str(&self) -> &'static str {
        match self {""")
    for name in SUBTYPE_ENUMS:
        var = name.replace("Type", "")
        print(f"            Subtype::{var}(v) => v.as_str(),")
    print("""        }
    }
}
impl core::fmt::Display for Subtype {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result { f.write_str(self.as_str()) }
}
impl core::str::FromStr for Subtype {
    type Err = ();
    fn from_str(s: &str) -> Result<Self, ()> {""")
    for name in SUBTYPE_ENUMS:
        print(f"        if let Ok(v) = s.parse::<{name}>() {{ return Ok(v.into()); }}")
    print("""        Err(())
    }
}
impl Serialize for Subtype {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> { s.serialize_str(self.as_str()) }
}
impl<'de> Deserialize<'de> for Subtype {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = String::deserialize(d)?;
        s.parse().map_err(|_| serde::de::Error::custom(format!("unknown subtype: {s}")))
    }
}""")


if __name__ == "__main__":
    main()
